core/urls.py
from django.urls import path
from .views import home, celery


urlpatterns = [
    path('', home, name='home'),
    path('celery/', celery, name='celery'),
]

funcionarios/urls.py
from django.urls import path
from .views import (
    FuncionarioList,
    FuncionarioUpdate,
    FuncionarioDelete,
    FuncionarioCreate,
    pdf_reportlab,
    Pdf
)


urlpatterns = [
    path('', FuncionarioList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioCreate.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', FuncionarioUpdate.as_view(), name='update_funcionario'),
    path('deletar/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('pdf-reportlab/', pdf_reportlab, name='pdf_reportlab'),
    path('pdf-xhtml/', Pdf.as_view(), name='pdf_xhtml'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Internacionalização
from django.conf.urls.i18n import i18n_patterns

# Django rest framework
from rest_framework import routers
from core import views

# APIs
from funcionarios.api.viewsets import FuncionarioViewSet
from registro_hora_extra.api.viewsets import RegistroHoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/horas-extras', RegistroHoraExtraViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns (
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('funcionarios/', include('funcionarios.urls')),
    path('documentos/', include('documentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('empresas/', include('empresas.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Django rest framework
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

documentos/models.py
from django.db import models
from django.urls import reverse

from funcionarios.models import Funcionario


# Create your models here.
class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario,on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        # Quando form é submetido, o django chama este método pra redirecionar o usuário caso não tenha
        # sido definido o success_url, por exemplo.
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

funcionarios/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.urls import reverse

from departamentos.models import Departamento
from empresas.models import Empresa


# Create your models here.
class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    # Cálculo do registro de horas extra do funcionário
    # @property
    def total_horas_extra(self):
        # Usar Aggregate Sum do django pra retornar a soma da hora extra
        return self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum'] or 0

registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from funcionarios.models import Funcionario


# Create your models here.
class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def __str__(self):
        return self.motivo

    def get_absolute_url(self):
        # Após edição da hora extra, retornando usuário para tela de edição do funcionário
        return reverse('update_funcionario', args=[self.funcionario.id])

funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from .models import Funcionario

# PDF with reportlab:
import io
from django.http import HttpResponse
from reportlab.pdfgen import canvas

# PDF with xhtml2pdf:
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

# TRANSLATE
from django.utils.translation import ugettext_lazy as _


# Create your views here.
class FuncionarioList(ListView):
    model = Funcionario
    template_name = 'funcionarios/list_funcionarios.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        Usando com tradução
        """
        context = super().get_context_data(**kwargs)
        context['report_button'] = _('Employee report')
        return context

    def get_queryset(self):
        """
        Sobrescrevendo o método para que retorne apenas os objetos filtrados pela empresa
        no qual o funcionário cadastrou / trabalha.
        """
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa=empresa_logada)
        return queryset


class FuncionarioUpdate(UpdateView):
    model = Funcionario
    template_name = 'funcionarios/form_funcionario.html'
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    template_name = 'funcionarios/delete_funcionario_confirmation.html'
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreate(CreateView):
    model = Funcionario
    template_name = 'funcionarios/form_funcionario.html'
    fields = ['nome', 'departamentos']
    success_url = reverse_lazy('list_funcionarios')

    # Quando novo funcionário é criado, é necessário criar um novo usuário, empresa etc. Override django método
    def form_valid(self, form):
        funcionario = form.save(commit=False)  # não salva no banco, apenas em memória
        funcionario.empresa = self.request.user.funcionario.empresa

        # Usando User do django pra criar usuário
        funcionario.user = User.objects.create(
            username=funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        )

        # Salvando funcionário
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


def pdf_reportlab(request):
    response = HttpResponse(content_type='application/pdf')

    # Baixar arquivo invés de abrir na página
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'

    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Eixo X - Y começa no canto inferior esquerdo da página
    # 10 representa da margem esquerda 10px
    # 810 representa debaixo pra cima, no topo da página
    p.drawString(250, 810, "Relatório de funcionários")

    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)
    str_funcionario = 'Nome: %s'

    y = 750
    for funcionario in funcionarios:
        p.drawString(10, y, str_funcionario % (funcionario.nome))
        y -= 20

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    # return FileResponse(buffer, as_attachment=True, filename='hello.pdf')
    return response


class Render:
    # Função base pra renderizar o PDF

    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode('UTF-8')), response)

        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf'
            )
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response

        else:
            return HttpResponse('Error rendering pdf', status=400)


class Pdf(View):
    def get(self, request):
        params = {
            'today': "Variável today",
            'sales': "Variável sales",
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

funcionarios/templates/funcionarios/delete_funcionario_confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Deletar {{object}}
{% endblock %}

{% block main %}
    <form action="" method="post" class="mt-5">
        {% csrf_token %}
        <p>Quer mesmo excluir o <b> {{object}} </b>? </p>
        <button type="submit" class="btn btn-danger"> Sim </button>
    </form>

{% endblock %}

funcionarios/templates/funcionarios/form_funcionario.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}

{% block title %}
  Editar Funcionário
{% endblock %}

{% block main %}
    <h1 class="display-5"> Funcionário </h1>
    <hr>

    <form action="" method="post">
        {% csrf_token %}
        {{form|bootstrap}}
        <button type="submit" class="btn btn-primary"> Salvar </button>
    </form>


    <!-- Listando todos os documentos desse funcionários -->
    <br>
    <h2 class="mt-5"> Documentos do {{object}} </h2>
    <a href="{% url 'create_documento' object.id %}" class="btn btn-primary">Adicionar documento</a>

    <ul>
        {% for documento in object.documento_set.all %}
            <!-- Acessando arquivo do funcionário pela url (shell) -->
            <li>  <a href="{{documento.arquivo.url}}"> {{documento}} </a> </li>
        {% endfor %}
    </ul>


    <!-- Listando hora extra desse funcionários -->
    <br>
    <h2 class="mt-3"> Hora extra </h2>
    <ul>
        {% for registro_hora in object.registrohoraextra_set.all %}
            <!-- Acessando hora extra do funcionário -->
            <li> <a href="{% url 'update_hora_extra' registro_hora.pk %}"> {{registro_hora.motivo}} </a> | {{registro_hora.horas}}h </li>
        {% endfor %}
    </ul>

    <!-- Listando somatório de hora extra desse funcionários -->
    <br>
    <h3>Somatório hora extra</h3>
    <p>Total: {{object.total_horas_extra}}h</p>

{% endblock %}

funcionarios/templates/funcionarios/list_funcionarios.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Funcionários
{% endblock %}

{% block main %}
    <h1 class="display-5"> Funcionários </h1>
    <a href="{% url 'create_funcionario' %}" class="btn btn-info"> Cadastrar funcionário </a>
<!--    <a href="{% url 'pdf_reportlab' %}" class="btn btn-primary"> Relatório funcionários </a>-->
    <a href="{% url 'pdf_reportlab' %}" class="btn btn-primary"> {{report_button}} </a>
    <a href="{% url 'pdf_xhtml' %}" class="btn btn-primary"> Relatório XHTML </a>
    <hr>

    {% for funcionario in object_list %}
        <p> <a href="{% url 'update_funcionario' funcionario.pk %}"> Nome: {{funcionario.nome}} </a> </p>
        <p> Empresa: {{funcionario.empresa}} </p>
        <p> <a href="{% url 'delete_funcionario' funcionario.pk %}"> Deletar </a> </p>
        <br>
    {% endfor %}

{% endblock %}

funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}

{% block title %}
  Relatório Funcionários
{% endblock %}

{% block main %}
    <h1> Relatório with XHTML2PDF </h1>
    <h2> {{sales}} </h2>

{% endblock %}